### ISSUE TITLE
Requirements (OpenCage and PHP intl extension)

### ISSUE THREAD

**Issue by teppokoivula** [neuerituale/FieldtypeGeocoder#2]
Hey there,

First of all, thanks for this module — seems like a brilliant solution!

Now, there were a couple of gotchas that I ran into while getting started, perhaps these are something you might want to mention in the documentation:

- The module requires PHP intl extension, without it AJAX requests fail silently (there's an error in the console, but regular users may not notice that). I've seen some packages work around similar requirement with alternate solutions, so that's likely doable, but I think it might be enough if this was mentioned in the README (and perhaps checked during installation?)
- I didn't find any notes about the default geolocation provider (OpenCage). It might be a good idea to specifically mention this, and perhaps add a note about that next to the module config API key input as well. Sure, users can change it with code, but currently it's a little unclear what the default value is.

Also, a small thing but the headline in the README is for FieldtypeOembed :)

Again: thanks for making this module available!

**Comment by julianwinkel** [comment]
Many Thanks. We have updated the readme. 

Do you have an example of an alternative solution for intl-support?

**Comment by teppokoivula** [comment]
Hey @julianwinkel, sorry for delayed response and thanks for updating README :)

> Do you have an example of an alternative solution for intl-support?

Honestly, no.

Earlier while I did some googling with the error it seemed that other projects had dealt with this somehow, but I didn't dig any deeper and now I can't even remember the exact error.

Had a quick look and it seems that while some libraries solve similar issues, none of those is likely a complete replacement: https://github.com/symfony/intl states that it only work for one locale (EN) and https://github.com/commerceguys/intl doesn't seem to offer all necessary features, etc. :)
